services:
  notification-service:
    build: .
    container_name: notification-service
    env_file:
      - /home/deploy/config/.env.common # Common environment variables
      - .env.staging
    ports:
      - "4010:4010"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
